name: RHSI-Install-demo

env:

  AWS_OPENSHIFT_SERVER: ${{ secrets.AWS_OPENSHIFT_API }}
  AWS_OPENSHIFT_TOKEN: ${{ secrets.AWS_OPENSHIFT_TOKEN }}
  AZURE_OPENSHIFT_SERVER: ${{ secrets.AZURE_OPENSHIFT_API }}
  AZURE_OPENSHIFT_TOKEN: ${{ secrets.AZURE_OPENSHIFT_TOKEN }}
  # 🖊️ EDIT to set the kube context's namespace after login. Leave blank to use your user's default namespace.
  OPENSHIFT_NAMESPACE: ""

  # 🖊️ EDIT to set a name for your OpenShift app, or a default one will be generated below.
  APP_NAME: ""

  # 🖊️ EDIT with the port your application should be accessible on.
  # If the container image exposes *exactly one* port, this can be left blank.
  # Refer to the 'port' input of https://github.com/redhat-actions/oc-new-app
  APP_PORT: ""

  # 🖊️ EDIT to change the image registry settings.
  # Registries such as GHCR, Quay.io, and Docker Hub are supported.
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}

  # 🖊️ EDIT to specify custom tags for the container image, or default tags will be generated below.
  IMAGE_TAGS: ""

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:
  push:
    # Edit to the branch(es) you want to build and deploy on each push.
    branches: [ "testing" ]

jobs:
  AWS:
    # 🖊️ Uncomment this if you are using CRDA scan step above
    # needs: crda-scan
    name: Install RHSI on AWS
    runs-on: ubuntu-20.04
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 4
              
    - name: Helm tool installer
      uses: Azure/setup-helm@v3

    # https://github.com/redhat-actions/oc-login#readme
    - name: Log in to aws OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.AWS_OPENSHIFT_SERVER }}
        openshift_token: ${{ env.AWS_OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        kubeconfig: /tmp/aws

    - name: Install RHSI
      run: |
        helm upgrade --install --create-namespace --namespace skupper \
               skupper charts/rhsi --set common.siteconfigonly=true
        helm upgrade --install --create-namespace --namespace skupper \
             skupper charts/rhsi --set common.siteconfigonly=false --set flowCollector.enabled=false \
             --set common.ingress.domain=apps.cluster-xnhcv.xnhcv.sandbox2273.opentlc.com

    - name: get link linkTokenCreate
      run: oc get secret skupper-link-token -n skupper -o yaml | grep -v creationTimestamp | grep -v namespace | grep -v uid | grep -v resourceVersion | grep -v "kubectl.kubernetes.io/last-applied-configuration"  > /tmp/connectiontoken.yaml

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3     
      with:
        name: linktoken
        path: /tmp/connectiontoken.yaml

  Azure:
    # 🖊️ Uncomment this if you are using CRDA scan step above
    # needs: crda-scan
    name: Install RHSI on Azure
    needs: AWS
    runs-on: ubuntu-20.04
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 4
              
    - name: Helm tool installer
      uses: Azure/setup-helm@v3

    - name: Log in to Azure OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.AZURE_OPENSHIFT_SERVER }}
        openshift_token: ${{ env.AZURE_OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        kubeconfig: /tmp/aws

    - name: Install RHSI on Azure
      run: |
        helm upgrade --install --create-namespace --namespace skupper \
               skupper charts/rhsi --set common.siteconfigonly=true
        helm  upgrade --install --create-namespace --namespace skupper \
             skupper charts/rhsi --set common.siteconfigonly=false --set flowCollector.enabled=false \
             --set common.ingress.domain=apps.azure-xnhcv-1.xnhcv-1.sandbox2512.opentlc.com

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: linktoken
        path: /tmp
            

    - name: Link To AWS Site
      run: |
        oc apply -n skupper -f /tmp/connectiontoken.yaml 